Data Preprocessing

step 1:** importing libraries**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

**step 2: Loading dataset**

In [2]:
df=pd.read_csv('/content/Employee.csv')

Data information

In [3]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4653 entries, 0 to 4652
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Education                  4653 non-null   object
 1   JoiningYear                4653 non-null   int64
 2   City                       4653 non-null   object
 3   PaymentTier                4653 non-null   int64
 4   Age                        4653 non-null   int64
 5   Gender                     4653 non-null   object
 6   EverBenched                4653 non-null   object
 7   ExperienceInCurrentDomain  4653 non-null   int64
 8   LeaveOrNot                 4653 non-null   int64
dtypes: int64(5), object(4)
memory usage: 327.3+ KB

,JoiningYear,PaymentTier,Age,ExperienceInCurrentDomain,LeaveOrNot
count,4653.000000,4653.000000,4653.000000,4653.000000,4653.000000
mean,2015.062970,2.698259,29.393295,2.905652,0.343864
std,1.863377,0.561435,4.826087,1.558240,0.475047
min,2012.000000,1.000000,22.000000,0.000000,0.000000
25%,2013.000000,3.000000,26.000000,2.000000,0.000000
50%,2015.000000,3.000000,28.000000,3.000000,0.000000
75%,2017.000000,3.000000,32.000000,4.000000,1.000000
max,2018.000000,3.000000,41.000000,7.000000,1.000000

In [4]:
df.head(10)

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1
5,Bachelors,2016,Bangalore,3,22,Male,No,0,0
6,Bachelors,2015,New Delhi,3,38,Male,No,0,0
7,Bachelors,2016,Bangalore,3,34,Female,No,2,1
8,Bachelors,2016,Pune,3,23,Male,No,1,0
9,Masters,2017,New Delhi,2,37,Male,No,2,0

**step 3: Handling missing values**

In [5]:
df.isnull().sum()

Education                    0
JoiningYear                  0
City                         0
PaymentTier                  0
Age                          0
Gender                       0
EverBenched                  0
ExperienceInCurrentDomain    0
LeaveOrNot                   0
dtype: int64

we don't have any missing values so don't need find mean,mode or median.

we don't require all features in order to build a prediction model ,we need to extract the necessary information to train our model from raw data (real data) .

In [7]:
df.head()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1

**step 4:  Encoding Categorical Data**
if categorical value types are <10 ----->
  we need to use "one hot encoding methos"
else:
  Frequency Encoding

In [8]:
df['City'].nunique()

3

In [9]:
df['City'].unique()

array(['Bangalore', 'Pune', 'New Delhi'], dtype=object)

In [10]:
df['City'].value_counts()

City
Bangalore    2228
Pune         1268
New Delhi    1157
Name: count, dtype: int64

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
le=LabelEncoder()
df['City']=le.fit_transform(df['City'])
df['Gender']=le.fit_transform(df['Gender'])
df['EverBenched']=le.fit_transform(df['EverBenched'])
df.head(10)

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,0,3,34,1,0,0,0
1,Bachelors,2013,2,1,28,0,0,3,1
2,Bachelors,2014,1,3,38,0,0,2,0
3,Masters,2016,0,3,27,1,0,5,1
4,Masters,2017,2,3,24,1,1,2,1
5,Bachelors,2016,0,3,22,1,0,0,0
6,Bachelors,2015,1,3,38,1,0,0,0
7,Bachelors,2016,0,3,34,0,0,2,1
8,Bachelors,2016,2,3,23,1,0,1,0
9,Masters,2017,1,2,37,1,0,2,0

In [13]:
df['Education'].unique()

array(['Bachelors', 'Masters', 'PHD'], dtype=object)

In [ ]:
df['Education'].value_counts()

Education
Bachelors    3601
Masters       873
PHD           179
Name: count, dtype: int64

In [16]:
df['Education']=le.fit_transform(df['Education'])
df.head(10)
df.drop('JoiningYear',axis=1,inplace=True)
df.head(10)

,Education,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,0,0,1.0,0.631579,1,0,0.000000,0
1,0,2,0.0,0.315789,0,0,0.428571,1
2,0,1,1.0,0.842105,0,0,0.285714,0
3,1,0,1.0,0.263158,1,0,0.714286,1
4,1,2,1.0,0.105263,1,1,0.285714,1
5,0,0,1.0,0.000000,1,0,0.000000,0
6,0,1,1.0,0.842105,1,0,0.000000,0
7,0,0,1.0,0.631579,0,0,0.285714,1
8,0,2,1.0,0.052632,1,0,0.142857,0
9,1,1,0.5,0.789474,1,0,0.285714,0

step 6: Normalization
why we need to normalization--->

In [17]:
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler()
df['Age']=sc.fit_transform(df[['Age']])
df['ExperienceInCurrentDomain']=sc.fit_transform(df[['ExperienceInCurrentDomain']])
df['PaymentTier']=sc.fit_transform(df[['PaymentTier']])

df.head(10)

,Education,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,0,0,1.0,0.631579,1,0,0.000000,0
1,0,2,0.0,0.315789,0,0,0.428571,1
2,0,1,1.0,0.842105,0,0,0.285714,0
3,1,0,1.0,0.263158,1,0,0.714286,1
4,1,2,1.0,0.105263,1,1,0.285714,1
5,0,0,1.0,0.000000,1,0,0.000000,0
6,0,1,1.0,0.842105,1,0,0.000000,0
7,0,0,1.0,0.631579,0,0,0.285714,1
8,0,2,1.0,0.052632,1,0,0.142857,0
9,1,1,0.5,0.789474,1,0,0.285714,0

**step 7: splitting **

In [18]:
from sklearn.model_selection import train_test_split

X = df.drop('LeaveOrNot', axis=1)
y = df['LeaveOrNot']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

step 8: train the models and calculating accuracy
Random forest model

In [19]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Initialize model
model = RandomForestClassifier(random_state=42)

# Train
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.7647690655209453
              precision    recall  f1-score   support

           0       0.77      0.91      0.84       610
           1       0.75      0.48      0.58       321

    accuracy                           0.76       931
   macro avg       0.76      0.70      0.71       931
weighted avg       0.76      0.76      0.75       931

SMOTE model

In [23]:
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

X_train, X_test, y_train, y_test = train_test_split(
    X_resampled, y_resampled, test_size=0.2, random_state=42
)

model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.71      0.82      0.76       618
           1       0.78      0.66      0.72       604

    accuracy                           0.74      1222
   macro avg       0.75      0.74      0.74      1222
weighted avg       0.75      0.74      0.74      1222